### PR TITLE
Added lombok annotations

### PR DESCRIPTION
**Pull request by DenuxPlays**
## Pull Request Etiquette

- [X] I have checked the PRs for upcoming features/bug fixes.

### Changes

- [x] Internal code
- [ ] Documentation
- [ ] Added examples
- [ ] Other: \_____

Closes Issue: #94 

## Description
Replaces some getter and setter method with one annotation.

### CODE REVIEW

**Comment by DynxstyGIT** [comment]
Re-add the deleted docs in DIH4JDAConfig pls

**Comment by DenuxPlays** [comment]
> Re-add the deleted docs in DIH4JDAConfig pls

then we can just remove lombok or what do you mean?

**Comment by DynxstyGIT** [comment]
No, add the docs to the variables itself

**Comment by DenuxPlays** [comment]
> No, add the docs to the variables itself

ok 👍

**Pull request merged**
